/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_david_learn_OpusTool */

#ifndef _Included_com_david_learn_OpusTool
#define _Included_com_david_learn_OpusTool
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_david_learn_OpusTool
 * Method:    nativeGetString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_david_learn_OpusTool_nativeGetString
  (JNIEnv *, jobject);

/*
 * Class:     com_david_learn_OpusTool
 * Method:    encodeWavFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_david_learn_OpusTool_encodeWavFile
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_david_learn_OpusTool
 * Method:    decodeOpusFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_david_learn_OpusTool_decodeOpusFile
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
